version: '3'
services:
  localstack:
    container_name: aws_localstack
    image: localstack/localstack
    environment:
      - SERVICES=sqs,s3,lambda,dynamodb,ssm,secretmanager,sns,rds
      - AWS_DEFAULT_REGION=sa-east-1
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"